### ISSUE TITLE
about gen_training_data /get_images_inputs.py ？

### ISSUE THREAD

**Issue by yhl2018** [wz0919/waypoint-predictor#1]
During data processing, the habitat_connectivity_graph directory does not contain tran.json
RAW_GRAPH_PATH= '/home/vlnce/habitat_connectivity_graph/%s.json'
NUMBER = 120

SPLIT = 'train'

with open(RAW_GRAPH_PATH%SPLIT, 'r') as f:
    raw_graph_data = json.load(f)

**Comment by wz0919** [comment]
Sorry for missing the files. I suppose the graph files in the D2C repo are the same as the RAW_GRAPH_PATH data but seems not. You can check them out here. https://drive.google.com/drive/folders/1wpuGAO-rRalPKt8m1-QIvlb_Pv1rYJ4x?usp=sharing
